require("user.launch")
require("user.options")
require("user.keymaps")
require("user.autocmds")
spec("user.colorscheme")
spec("user.devicons")
spec("user.whichkey")
spec("user.treesitter")
spec("user.nvimtree")
spec("user.telescope")
spec("user.toggleterm")
spec("user.gitsigns")
spec("user.mason")
spec("user.schemastore")
spec("user.lspconfig")
spec("user.none-ls")
spec("user.cmp")
-- -- spec("user.rust-tools")
spec("user.illuminate")
spec("user.comment")
spec("user.crates")
spec("user.lualine")
spec("user.navic")
spec("user.breadcrumbs")
-- spec("user.harpoon")
spec("user.markdown")
spec("user.rainbow-csv")
spec("user.autopairs")
spec("user.neogit")
spec("user.alpha")
spec("user.project")
-- spec("user.indentline")
spec("user.hlslens")
spec("user.scrollbar")
spec("user.colorizer")
spec("user.extras.ufo")
-- spec "user.extras.copilot"
-- spec "user.extras.neoscroll"
require("user.lazy")
